In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# %reload model

# from model import model_parts as mp
from model import ProtENN2_style

In [7]:
import numpy as np
import torch

model = ProtENN2_style()

test_input = torch.rand(64, 100, 21)

output = model(test_input)

In [4]:
print(output.shape)

print(torch.sum(output, axis=-1).shape)

torch.Size([64, 100, 628])
torch.Size([64, 100])


In [3]:
import pandas as pd

dataset_df = pd.read_pickle("../../dataset/dataset.pkl")  
dataset_df

,pfam_tensor,sequence
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...
...,...,...
U4UHL9,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKGITSNKLLCGNRFLNLLDSRPQLPTT...
A0A6J2XE68,"[None, None, None, None, None, None, None, Non...",MANVNTDLTEEDAADLQFPKDSTSQIPTTSTLVNVSDKNVILGYCS...
A0A834MIF3,"[None, None, None, None, None, None, None, Non...",MANVNTDLTEEDAADLQFPKDATSQKPSTSSVVNVSDKSIILGYCS...
A0A653BD21,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKADELAKTTLSYVSTNTFLDNPDSSYC...


In [4]:
# filter out sequences with more than 500 amino acids
dataset_df["seq_len"] = dataset_df["sequence"].apply(lambda x: len(x))
dataset_df = dataset_df[dataset_df["seq_len"] <= 500]
dataset_df

,pfam_tensor,sequence,seq_len
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221
...,...,...,...
A0A4U5NBC5,"[None, None, None, None, None, None, None, Non...",MTDSSPHLKRDEVVRQCCICISTLNGACIKCVECKRKTTFLCVPCF...,419
U4UHL9,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKGITSNKLLCGNRFLNLLDSRPQLPTT...,474
A0A6J2XE68,"[None, None, None, None, None, None, None, Non...",MANVNTDLTEEDAADLQFPKDSTSQIPTTSTLVNVSDKNVILGYCS...,460
A0A653BD21,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKADELAKTTLSYVSTNTFLDNPDSSYC...,462


In [5]:
subset_df = dataset_df.head(10000)
subset_df

,pfam_tensor,sequence,seq_len
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221
...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99


In [6]:
# Save sequences to fasta file
from Bio import SeqIO
from Bio.Seq import Seq

# create column if from index
subset_df["id"] = subset_df.index.astype(str)

with open("test_sequences.fasta", "w") as fasta_file:
    for index, row in subset_df.iterrows():
        seq = Seq(row["sequence"])
        record = SeqIO.SeqRecord(seq, id=row["id"], description="")
        SeqIO.write(record, fasta_file, "fasta")



/tmp/ipykernel_2992514/1764927560.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df["id"] = subset_df.index.astype(str)


In [ ]:
from Bio import SeqIO

fasta_path = "../../dataset/easy_subset_19k.fasta"  # update with your file path

headers = [record.id for record in SeqIO.parse(fasta_path, "fasta")]
print(headers)

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/easy_subset_19k.fasta'

In [8]:
from model_parts import CUSTOM_ALPHABET
from model import MAX_PROTEIN_LENGTH

# one hot encode sequences and pad to max length
def one_hot_encode(sequence, alphabet=CUSTOM_ALPHABET, max_length=MAX_PROTEIN_LENGTH):
    one_hot = np.zeros((max_length, len(alphabet)), dtype=np.float32)
    for i, char in enumerate(sequence):
        # padding is done with tensor [1,0,0,...]
        if i < max_length and char in alphabet:
            one_hot[i, alphabet[char]] = 1.0
    
    return one_hot

# apply one hot encoding to sequences
subset_df["one_hot"] = subset_df["sequence"].apply(one_hot_encode)

subset_df


/tmp/ipykernel_391859/2064692852.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df["one_hot"] = subset_df["sequence"].apply(one_hot_encode)


,pfam_tensor,sequence,seq_len,one_hot
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
...,...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."


In [20]:
len(subset_df["pfam_tensor"].explode().unique())


pfam_to_index = {pfam: idx+1 for idx, pfam in enumerate(subset_df["pfam_tensor"].explode().unique())}

pfam_to_index


{None: 1,
 'PF10417.14': 2,
 'PF00578.27': 3,
 'PF21734.3': 4,
 'PF09847.15': 5,
 'PF00244.26': 6,
 'PF16998.10': 7,
 'PF00389.36': 8,
 'PF02826.25': 9,
 'PF02817.22': 10,
 'PF00198.28': 11,
 'PF00364.28': 12,
 'PF16078.10': 13,
 'PF04029.19': 14,
 'PF04463.17': 15,
 'PF13302.13': 16,
 'PF01288.25': 17,
 'PF08349.16': 18,
 'PF05635.17': 19,
 'PF22546.2': 20,
 'PF22545.2': 21,
 'PF08521.16': 22,
 'PF08793.15': 23,
 'PF20150.5': 24,
 'PF11591.13': 25,
 'PF01257.25': 26,
 'PF08975.16': 27,
 'PF22547.2': 28,
 'PF03390.20': 29,
 'PF21584.2': 30,
 'PF03171.26': 31,
 'PF14226.12': 32,
 'PF10637.15': 33,
 'PF13532.12': 34,
 'PF13640.12': 35,
 'PF08336.16': 36,
 'PF18331.6': 37,
 'PF13661.12': 38,
 'PF13759.12': 39,
 'PF20515.4': 40,
 'PF10014.15': 41,
 'PF13239.11': 42,
 'PF06580.19': 43,
 'PF23143.1': 44,
 'PF13563.12': 45,
 'PF06983.19': 46,
 'PF06052.18': 47,
 'PF01073.25': 48,
 'PF14934.11': 49,
 'PF06725.17': 50,
 'PF03562.22': 51,
 'PF03990.20': 52,
 'PF07501.17': 53,
 'PF01471.23': 54,


In [9]:
# get unique pfam_ids
unique_pfams = set()

for pfam_list in subset_df["pfam_tensor"]:
    for pfam in pfam_list:
        unique_pfams.add(pfam)

# create a mapping from pfam_id to index
pfam_to_index = {pfam: i for i, pfam in enumerate(unique_pfams)}

# one hot encode pfam tensors and pad to max length
def pad_pfam_tensor(pfam_tensor, max_length=MAX_PROTEIN_LENGTH):
    padded_tensor = np.zeros((max_length,len(pfam_to_index)), dtype=np.float32)
    for i, pfam in enumerate(pfam_tensor):
        if i < max_length:
            padded_tensor[i, pfam_to_index.get(pfam, 0)] = 1.0  # use 0 for unknown pfams
    return padded_tensor

# apply one hot encoding to pfam tensors
subset_df["pfam_one_hot"] = subset_df["pfam_tensor"].apply(pad_pfam_tensor)

subset_df

/tmp/ipykernel_391859/2085954855.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df["pfam_one_hot"] = subset_df["pfam_tensor"].apply(pad_pfam_tensor)


,pfam_tensor,sequence,seq_len,one_hot,pfam_one_hot
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
...,...,...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."


In [17]:
pfam_to_index

{'PF06615.16': 0,
 'PF08796.15': 1,
 'PF10439.15': 2,
 'PF16121.10': 3,
 'PF06698.16': 4,
 'PF06620.16': 5,
 'PF07043.18': 6,
 'PF00779.24': 7,
 'PF16860.10': 8,
 'PF12966.13': 9,
 'PF07125.16': 10,
 'PF16689.10': 11,
 'PF08991.16': 12,
 'PF15355.11': 13,
 'PF00313.28': 14,
 'PF05627.16': 15,
 'PF09713.15': 16,
 'PF02627.25': 17,
 'PF08742.16': 18,
 'PF08979.16': 19,
 'PF22586.1': 20,
 'PF12121.13': 21,
 'PF00895.25': 22,
 'PF07076.17': 23,
 'PF08026.16': 24,
 'PF07210.18': 25,
 'PF08846.15': 26,
 'PF17866.7': 27,
 'PF02805.21': 28,
 'PF01313.24': 29,
 'PF21825.2': 30,
 'PF20829.2': 31,
 'PF12133.13': 32,
 'PF04940.18': 33,
 'PF18277.6': 34,
 'PF05293.16': 35,
 'PF00228.25': 36,
 'PF15116.11': 37,
 'PF06568.16': 38,
 'PF03777.18': 39,
 'PF09048.16': 40,
 'PF07369.16': 41,
 'PF04691.17': 42,
 'PF05968.16': 43,
 'PF13318.11': 44,
 'PF22754.3': 45,
 'PF06639.16': 46,
 'PF09082.15': 47,
 'PF09707.15': 48,
 'PF10438.15': 49,
 'PF03992.22': 50,
 'PF20520.3': 51,
 'PF17793.6': 52,
 'PF08109.1

In [61]:
subset_df

,pfam_tensor,sequence,seq_len,one_hot,pfam_one_hot
G2Z1S9,"[None, None, None, None, None, None, None, Non...",MENYNQIDERYIAAQKRVQEIKGFYGHLASYVLVNLFLLILNLVSS...,96,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4CNS3,"[None, None, None, None, None, None, None, Non...",MEDFKKESKYIRARERVEELKKFYGNVASYIFVITLLGIINYLTYW...,100,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
G0L8V4,"[None, None, None, None, None, None, None, PF1...",MERESKYIRAKERVEREKKFYNGLISYVVTISFLAAINYYTNGFAY...,97,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4CNS4,"[None, None, None, None, None, None, None, Non...",MEDFSHADRYLRAKKRVEDIRGFYGNLITYLIVIPFLIWLNWRTTS...,93,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
F9YQQ0,"[None, None, None, None, None, None, None, Non...",MNTIEPNAYRKAEKRVKKLKKFYHHLATYVVVNTFLVGLNLYQTPN...,93,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
...,...,...,...,...,...
Q1GQN9,"[None, None, PF09413.15, PF09413.15, PF09413.1...",MPLVELVRLPNGAEAELLRGRLESAGVHAVCFDAGMNIAESVGLMI...,70,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
F8KZY9,"[None, None, None, PF09413.15, PF09413.15, PF0...",MNNFVCIYRTFDIVQANLIKSHFENEDILCVLKSNDASGILPHLGF...,74,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A8F8N0,"[None, PF09413.15, PF09413.15, PF09413.15, PF0...",MWRILLEEVDLPTANILKSLLEESGIEVLIKPGSFDPVIFGQGGLV...,74,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q8A1E5,"[None, None, None, None, None, None, None, PF0...",MKEEDYSKAIEVFSGSPWEAEIIKGLLESNDIRCVIKDGIMGTLAP...,77,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."


In [83]:
example_input = torch.tensor(np.stack(subset_df["one_hot"].values[:64]), dtype=torch.float32)

model = ProtENN2_style(num_pfams=len(pfam_to_index))

# example_input.shape

model(example_input).shape

torch.Size([64, 100, 628])

In [84]:
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[:64]), dtype=torch.float32)

example_output.shape

torch.Size([64, 100, 628])

In [12]:
Y_onehot = np.stack(subset_df["pfam_one_hot"].values[:5000])  # (batch, 100, num_pfams)

Y = torch.tensor(Y_onehot.argmax(axis=-1), dtype=torch.long)

Y

tensor([[ 19,  19,  19,  ...,  19,  19,  19],
        [ 19,  19,  19,  ...,   4,   4,   4],
        [ 19,  19,  19,  ...,   4,   4,   4],
        ...,
        [ 19,  19,  19,  ..., 248, 248, 248],
        [ 19,  19,  19,  ..., 248, 248, 248],
        [ 19,  19,  19,  ..., 248, 248, 248]])

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# Prepare data
X = torch.tensor(np.stack(subset_df["one_hot"].values[:5000]), dtype=torch.float32)  # (batch, 100, 21)
Y_onehot = np.stack(subset_df["pfam_one_hot"].values[:5000])  # (batch, 100, num_pfams)
Y = torch.tensor(Y_onehot.argmax(axis=-1), dtype=torch.long)  # (batch, 100)

dataset = TensorDataset(X, Y)
loader = DataLoader(dataset, batch_size=250, shuffle=True)

model = ProtENN2_style(num_pfams=Y_onehot.shape[-1])
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss()  # expects (N, C) and (N,) or (N, d1, d2, ...) and (N, d1, d2, ...)

# Training loop
for epoch in range(40):
    model.train()
    total_loss = 0
    for xb, yb in loader:
        optimizer.zero_grad()
        out = model(xb)  # (batch, 100, num_pfams)
        loss = criterion(out.view(-1, out.shape[-1]), yb.view(-1))  # flatten for CrossEntropyLoss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.4f}")

Epoch 1, Loss: 3.6660


KeyboardInterrupt: 

In [47]:
n=1111

example_input = torch.tensor(np.stack(subset_df["one_hot"].values[n:n+1]), dtype=torch.float32)
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[n:n+1]), dtype=torch.float32)

output = model(example_input)

# print all values in the output tensor into console
output = output.view(-1, output.shape[-1])  # flatten for easier viewing
output = output.argmax(axis=-1)  # get the predicted class indices

print(output.shape)
print(output)

# Convert output to numpy array for easier viewing
example_output = example_output.view(-1, example_output.shape[-1])  # flatten for easier viewing
example_output = example_output.argmax(axis=-1)  # get the true class indices
print(example_output.shape)
print(example_output)

# output = output.detach().numpy()

# print(list(output))

# print values at these indexes


torch.Size([100])
tensor([326, 326, 326, 326,   0,   0,   0,   0,   0,   0,   0, 479, 326, 326,
        326, 326, 326, 326, 326, 326, 326, 407, 407, 326, 170, 242, 407, 407,
        467, 614,   0, 371,   0,  98,  98,  98,  98,  22,  22, 111, 111,   0,
        564, 564,  22, 157,  39,  39,  98,  98,  22, 326, 453,  39, 602, 174,
        127, 127, 403, 157, 524, 111,  98, 293, 149,  98, 242, 326, 326,  98,
         98,  98, 326, 561, 326, 539, 539, 539, 242, 539, 539, 372, 326, 326,
        242, 564, 358, 358, 358, 358, 349, 326, 326, 122, 326, 326, 326, 326,
          0,   0])
torch.Size([100])
tensor([326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326,
        326, 326, 326, 326, 326, 326, 326, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
        1

In [48]:
print([int(i) for i in output.numpy()])
print([int(i) for i in example_output.numpy()])

[326, 326, 326, 326, 0, 0, 0, 0, 0, 0, 0, 479, 326, 326, 326, 326, 326, 326, 326, 326, 326, 407, 407, 326, 170, 242, 407, 407, 467, 614, 0, 371, 0, 98, 98, 98, 98, 22, 22, 111, 111, 0, 564, 564, 22, 157, 39, 39, 98, 98, 22, 326, 453, 39, 602, 174, 127, 127, 403, 157, 524, 111, 98, 293, 149, 98, 242, 326, 326, 98, 98, 98, 326, 561, 326, 539, 539, 539, 242, 539, 539, 372, 326, 326, 242, 564, 358, 358, 358, 358, 349, 326, 326, 122, 326, 326, 326, 326, 0, 0]
[326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326]


In [61]:
n = 90

example_input = torch.tensor(np.stack(subset_df["one_hot"].values[n:n+1]), dtype=torch.float32)
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[n:n+1]), dtype=torch.float32)

# Get raw output from model
raw_output = model(example_input)

# Flatten for easier viewing
raw_output_flat = raw_output.view(-1, raw_output.shape[-1])
predicted_indices = raw_output_flat.argmax(axis=-1)

# Print shape and predicted indices
print("Predicted class indices:", predicted_indices.shape)
print(predicted_indices)

# Print the actual values that argmax selected
predicted_values = raw_output_flat[torch.arange(raw_output_flat.shape[0]), predicted_indices]
print("Values selected by argmax:", predicted_values)

# For the true labels
example_output_flat = example_output.view(-1, example_output.shape[-1])
true_indices = example_output_flat.argmax(axis=-1)
print("True class indices:", true_indices.shape)
print(true_indices)

# If desired: values selected in ground truth as well (normally one-hot encoded so should be 1.0)
true_values = example_output_flat[torch.arange(example_output_flat.shape[0]), true_indices]
print("True values from one-hot:", true_values)


Predicted class indices: torch.Size([100])
tensor([314, 314, 314, 314, 391, 391, 391, 391, 391, 391, 394, 394, 394, 394,
        394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394,
        149, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472,
        472, 472, 472,   3,   3, 314, 314, 314, 314, 314, 314, 314, 314, 314,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  50])
Values selected by argmax: tensor([ 7.4277,  7.3095,  8.2424,  7.2051,  8.4760, 11.4314,  9.3244,  8.5534,
         8.4048, 10.7787, 12.2779, 15.0474, 15.1132, 16.4672, 14.4989, 14.3691,
        11.8976, 15.2778, 15.9507, 13.6095, 10.8907,  7.7734,  9.9249, 14.2727,
        15.3568, 12.3570,  8.4824,  3.9467,  2.3888,  2.3025,  3.0961,  3.5697,
         3.1835,  6.9824,  6.9600,  8.3402,  

In [25]:
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[11:12]), dtype=torch.float32)

example_output = example_output.view(-1, example_output.shape[-1])  # flatten for easier viewing
example_output = example_output.argmax(axis=-1)  # get the true class indices
print(example_output.shape)
print(example_output)

torch.Size([100])
tensor([314, 314, 314, 314, 314, 314, 314, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 314, 314, 314, 314,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0])


In [32]:
np.set_printoptions(threshold=10_000)
torch.set_printoptions(profile="full")

example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[11:12]), dtype=torch.float32)
print(example_output)

example_output = example_output.view(-1, example_output.shape[-1])  # flatten for easier viewing
example_output = example_output.argmax(axis=-1)  # get the true class indices



tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [38]:
import hashlib

def tensor_hash(tensor: torch.Tensor) -> str:
    # Ensure tensor is on CPU and in a consistent dtype
    tensor = tensor.detach().cpu()
    # Convert to contiguous bytes
    tensor_bytes = tensor.numpy().tobytes()
    # Compute SHA-256 hash
    return hashlib.sha256(tensor_bytes).hexdigest()

In [40]:
tmp = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[12:13]), dtype=torch.float32)

tensor_hash(tmp)

'deb3028ba7b32029ab99ec5199561004bfca9dfae2e4071e0c056a636e5e0ebd'